# Generated by Django 6.0.7 on 2026-07-18 03:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must contain 7 to 15 digits and may start with '+'.", regex='^\\+?\\d{7,15}$')])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'name'], name='contacts_co_owner_i_1287e0_idx'), models.Index(fields=['owner', 'email'], name='contacts_co_owner_i_d0f936_idx'), models.Index(fields=['owner', 'phone_number'], name='contacts_co_owner_i_22dd51_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'email'), name='unique_email_per_owner'), models.UniqueConstraint(fields=('owner', 'phone_number'), name='unique_phone_per_owner')],
            },
        ),
    ]
